Add WorldEdit integration to AdvancedPortals
sekwah41/Advanced-Portals pull request #307
Opened 2021-12-12 20:50 UTC by JOO200

As mentioned here, you're fine with a WorldEdit integration.
https://github.com/sekwah41/Advanced-Portals/issues/44

And I want to add it in this PR.

I really like AdvancedPortals but too many wands are terrible. I added a config option to enable WorldEdit integration.
With that option:
- AdvancedPortals uses the WorldEdit selections (has to be a cuboid selection, uses the same player world. This is a limitation but imo it's not that big problem. 
- Disable /portal wand and /portal selector when WorldEdit integration is active

When WorldEdit is installed:
- Add /portal we-selection <name> to select the portal as worldedit selection

WorldEdit is marked as soft-depend, you don't need to install worldedit for AdvancedPortals.

2021-12-13 02:06 UTC, sekwah41 commented
I need to do some manual checks as some large chunks of code have been altered as well as the velocity library build version had been also modified as part of the same pr.

I've added it to my calendar for tomorrow afternoon so I should be able to review this after work.

2021-12-13 10:48 UTC, JOO200 commented
Yes, I had to update the Velocity version. I was unable to compile AdvancedPortals without that. You can remove this version update but I didn't need any code changes for that.

2021-12-14 02:07 UTC, sekwah41 requested changes

2021-12-14 02:08 UTC, sekwah41 commented
> Yes, I had to update the Velocity version. I was unable to compile AdvancedPortals without that. You can remove this version update but I didn't need any code changes for that.

I believe they may have removed some old versions because they wanted to force people over, it may also be because the old ones were vulnerable to log4shell attacks.

2021-12-15 00:13 UTC, sekwah41 approved these changes

2021-12-15 00:13 UTC, merged